### ISSUE TITLE
Resample_data quiz incorrect test results

### ISSUE THREAD

**Issue by xtr33me** [udacity/aitnd-issues#1]
I might be wrong here but it seems that the quiz_tests unit test for this notebook is incorrect. This is based on what I was seeing in the data, but please forgive me if I'm wrong. 

In the cell I used:
return open_prices.resample('W').last(), high_prices.resample('W').last(), low_prices.resample('W').last(), close_prices.resample('W').last()

I have just reduced the error log to just the "INPUT low prices", however it seems they were all incorrect except for the close.

Please note the "INPUT VALUES", "OUTPUT VALUES", and "EXPECTED OUTPUT"

Refer to 2018-10-14 for a date to look at.

AssertionError: Wrong value for days_to_weeks.

...
INPUT low_prices:
            XXWZ  QFH  HXE
2018-10-10    12   12   13
2018-10-11    12   14   15
2018-10-12    13   14   12
2018-10-13    14   14   13
2018-10-14    12   12   14
...

OUTPUT low_prices_weekly:
            XXWZ  QFH  HXE
2018-10-14    12   12   14
2018-10-21    13   14   16
2018-10-28    14   12   12
2018-11-04    12   12   13
2018-11-11    16   12   14
....
EXPECTED OUTPUT FOR low_prices_weekly:
            XXWZ  QFH  HXE
2018-10-14    12   12   12
2018-10-21    12   12   12
2018-10-28    12   12   12
2018-11-04    12   12   12
2018-11-11    12   12   12

**Comment by xtr33me** [comment]
Ok....so I looked at the notebook that you provided with the answer and I misunderstood what was wanted.  Sorry for wasting your time.

**Comment by xtr33me** [comment]
I tried closing it but seems I cant.

**Comment by Brok-Bucholtz** [comment]
Closed it, since it looks like you figured it out.
