### ISSUE TITLE
Install libraries failed on Lesson 28 Alpha Factor Research Method

### ISSUE THREAD

**Issue by aa-wong** [udacity/aitnd-issues#103]
Error returned the following 

"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mmzukpvt/tables/

You are using pip version 9.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'pip install --upgrade pip' command."

**Comment by aa-wong** [comment]
Additional details:

ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

**Comment by Brok-Bucholtz** [comment]
Duplicate of issue #102.

**Comment by Brok-Bucholtz** [comment]
This should be working again.
