### ISSUE TITLE
Error when running first cell of project 4 to install packages.

### ISSUE THREAD

**Issue by guireif** [udacity/aitnd-issues#104]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0m8fq6so/tables/
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by AdrianoW** [comment]
We have already mapped the problem with the table package. 
@Brok-Bucholtz is working on it

**Comment by Brok-Bucholtz** [comment]
Duplicate of issue #102.
