### ISSUE TITLE
error when installing library in lesson 24

### ISSUE THREAD

**Issue by max0303** [udacity/aitnd-issues#105]

**Comment by max0303** [comment]
Complete output from command python setup.py egg_info:
    /tmp/H5closenmn2omb4.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    /tmp/H5closenmn2omb4.c: In function ‘main’:
    /tmp/H5closenmn2omb4.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
         H5close();
         ^~~~~~~
    * Using Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:56)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k1fz6p9e/tables/
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' comman

**Comment by Brok-Bucholtz** [comment]
This should be working again.
