### ISSUE TITLE
Term1 Lesson 24: After installng requirements there is an error while importing pandas

### ISSUE THREAD

**Issue by f4usto** [udacity/aitnd-issues#114]
On Lesson 24: Part 04 

After executing:

import sys !{sys.executable} -m pip install -r requirements.txt

i am encountering an error on the next cell while importing pandas:

----> 2 import pandas as pd
(...)
---> 25     from pandas import hashtable, tslib, lib
(...)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216.

I have tried to refresh the workspace, but It did not fix the issue.

**Comment by sankhaMukherjee** [comment]
I faces pretty much the same problem. I manually installed the stuff from `requirements.txt`

```bash
import sys
!pip install --upgrade pip
!pip install --upgrade numpy
!pip install --upgrade pandas
!pip install --upgrade scikit-learn
!pip install --upgrade six
!pip install --upgrade zipline
# !{sys.executable} -m pip install -r requirements.txt
```

Seems to be working.  (Make sure to restart the kernel before you do the above)

**Comment by f4usto** [comment]
It didi work @sankhaMukherjee. Thank you. 
Do you have any idea to why the requirements do not work? because of some version incompatibility?

Thanks again
