### ISSUE TITLE
Switch to Slack

### ISSUE THREAD

**Issue by supertradr** [udacity/aitnd-issues#13]
Please switch to Slack vs the chat app like other NanoDegrees. The chat app is hard to use for a multitude of reasons:

- UI covering content on page
- Hard to find messages in general
- Hard to see which threads you are tagged in
- Can not search for content (chats, keywords, users, etc)
- ... and more.

**Comment by footfalcon** [comment]
I agree with this. An FAQ channel for each project cannot be created by the mentors. There is no search. You cannot star/bookmark messages for easy later reference. Etc.

**Comment by supertradr** [comment]
It doesn't work on mobile either (app or mobile web).

**Comment by xmindata** [comment]
Cannot agree more, this chat room is very hard to use. And no way to find the right topic. The forum  will be much easier to use.

**Comment by e7dud7e** [comment]
We agree that slack is great, but we don't have control over this.  The engineering teams are working on enhancing the chat features.  For example, the current chat "study hub" is now a full screen window.  We hope that you can still continue to engage with your classmates and mentors as much as possible. Thanks!
