### ISSUE TITLE
project 1 notebook

### ISSUE THREAD

**Issue by sergei3000** [udacity/aitnd-issues#14]
the function project_helper.print_dataframe(close) doesn't print anything

**Comment by Brok-Bucholtz** [comment]
Are you still getting this error? I'm not able to reproduce it.

**Comment by sergei3000** [comment]
It appeared from time to time. I don't know how to reproduce it for sure.
Did not meet anything like that in the second project.

**Comment by juanudacity** [comment]
Can't reproduce.
