### ISSUE TITLE
Project 1, function 'portfolio_returns': Can't understand why we need to divide the result by n_stocks

### ISSUE THREAD

**Issue by sergei3000** [udacity/aitnd-issues#15]
I can't understand, why in the project we need to divide the final results by 'n_stocks' in the function 'portfolio_returns'.

If we multiply lookahead returns by the binary df's, we get returns of each stock for each date already. Why divide by n_stock?

Or is it just some convention to use in the next cell ('View Data'), where to get the average returns for each day we just sum up all the tickers' returns from the function 'portfolio_returns'?

If this is the case, then all this is not really intuitive. I suggest in this case there should not be this division by 'n_stocks' in 'portfolio_returns', but instead it should be implemented in the next cell in 'plot_returns' by dividing the transposed sum by 2*top_bottom_n.

**Comment by Brok-Bucholtz** [comment]
For questions, please post at [https://knowledge.udacity.com](https://knowledge.udacity.com).
