### ISSUE TITLE
Notebook + Quiz: Simulating from the Null, Workspace not work.

### ISSUE THREAD

**Issue by binliu-base** [udacity/aitnd-issues#21]
Extracurricular-Statistics-Lesson12 Hypothesis Testing -15 Notebook + Quiz: Simulating from the Null

**Comment by binliu-base** [comment]
Location:  
Extracurricular-Statistics-Lesson12 Hypothesis Testing -15 Notebook + Quiz: Simulating from the Null

Problem:
![l12 15 1](https://user-images.githubusercontent.com/24623272/44861565-59285280-acab-11e8-84ee-c909bf79a7a1.PNG)

The workspace is not shown up,  I try to restore the workspace by input "Reset data", but the problem still shows up.

**Comment by Brok-Bucholtz** [comment]
Are you still seeing this error?

**Comment by binliu-aipnd** [comment]
close the bug due to the issue not be reproduced.
