### ISSUE TITLE
Latex display error

### ISSUE THREAD

**Issue by Aengelus** [udacity/aitnd-issues#22]

**Comment by Aengelus** [comment]
There is a latex display error for a mu.
See attached screenshot

![latex_display_error.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b880ecec48f3f00134fb441/125516c66e82c728ace21e0d46e4958e269abcad86faaf4fa544cf913b5428616b48e13b628ae92dbc56395b4d5a1cab15095b4dfbf98e7fafe23c708a5d59edd13f5b74942f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e48e894b3d1a06108eff5f27ed.PNG)

**Comment by juanudacity** [comment]
Thanks for noticing. It is fixed.
