### ISSUE TITLE
Explanation of PDF in Lesson 10 is not accurate

### ISSUE THREAD

**Issue by sergei3000** [udacity/aitnd-issues#24]
The video "Parameters of a Distribution" in Lesson 10 says that for any number the PDF gives a probability of this number, which is not true.

The probability of a continuous random variable taking any particular value is 0.

Instead, at any given value of a random variable the PDF can be interpreted as providing a RELATIVE LIKELIHOOD of that value of the random variable, which is not the same as the probability of such value.

**Comment by e7dud7e** [comment]
Thanks Sergei! I've updated this with a text below this video. Cheers!
