### ISSUE TITLE
notebook cumsum_and_cumprod in lesson 15 (stocks, funds, ...)

### ISSUE THREAD

**Issue by sergei3000** [udacity/aitnd-issues#28]
In Module 3 Lesson 15 Quiz 16: Rate of Returns Over Multiple Periods, are the calc for daily returns not lined up to the wrong month?, placing the NaN in the last month of the year instead of the first month of the year:

'''returns = (abc_close.shift(-1)/abc_close).dropna()'''

In abc_close we are given month-end prices, so we should be able to calculate the returns for each month except the first month (Jan-16) because we don’t have the previous month-end price (Dec-15). The following formula does this correctly:

'''returns = abc_close.pct_change(1)+1'''

**Comment by Brok-Bucholtz** [comment]
Thanks for letting us know. We've fixed the issue.
