### ISSUE TITLE
another issue with notebook cumsum_and_cumprod

### ISSUE THREAD

**Issue by sergei3000** [udacity/aitnd-issues#29]
the notebook cumsum_and_cumprod says:

"Assume the returns over n successive periods are:

r1,r2,r3,r4,r5,...,rn

The cumulative return of stock ABC over period n is the compounded return over period n:

(1+r1)(1+r2)(1+r3)(1+r4)(1+r5)...(1+rn)"

There should be "- 1" in the end, right?

**Comment by Brok-Bucholtz** [comment]
This is a duplicate of issue #27.

**Comment by Brok-Bucholtz** [comment]
Thanks for letting us know. We've fixed the issue.
