### ISSUE TITLE
Quiz: Stock Data csv_to_close

### ISSUE THREAD

**Issue by clankford** [udacity/aitnd-issues#3]
In the quiz section of the notebook it says "## Quiz
Let's see if you can apply what you learned. Implment the `csv_to_pivot` function to take in a filepath, `csv_filename`, and output the close 2d array. You can assume the CSV file used by `csv_to_close` has the same field names as "prices.csv" and in the same order."

Where it says csv_to_pivot it should say csv_to_close.

**Comment by juanudacity** [comment]
Thanks for noticing this. It should be fixed.
