### ISSUE TITLE
Confusion in "Formulating Portfolio Opt Problem" Quiz

### ISSUE THREAD

**Issue by xtr33me** [udacity/aitnd-issues#32]
In the "Portfolio Optimization" Module, number 6 "Formulating Portfolio Optimization Problems" quiz at the bottom I found the question to be confusing. I understood the answer, but the question through me off as they asked whether a "larger" lambda would give more priority to "minimizing" the first term or the second term.  If you have a larger lambda your second term would have more weight since it is multiplied by the second term which in my head would "minimize" the first term.  Yet second term was the answer.  The answer description provided once answered made total sense to me and was around the weighting on the second term being higher.  This again was just confusing to me so thought I would let you know.

**Comment by lizotto** [comment]
Thanks for letting us know!

**Comment by lizotto** [comment]
I've updated this quiz.
