### ISSUE TITLE
Project 2: expected values include last day

### ISSUE THREAD

**Issue by ayatsuro** [udacity/aitnd-issues#5]
The requirement says _Make sure this doesn't include the current day._ So we assume the last row is the current day.
If we look at the expected values for lookback_high:
```
 'lookback_high',
            pd.DataFrame(
                [
                    [np.nan, np.nan, np.nan],
                    [np.nan, np.nan, np.nan],
                    [92.11310000, 91.05430000, 90.95720000],
                    [92.11310000, 91.05430000, 90.95720000]],
                dates, tickers)),
```
It includes the last row.
So we if implement get_high_low_loopback to exclude the last row:
```
def get_high_lows_lookback(high, low, lookback_days):
    rhigh = high.iloc[:-1, :].rolling(window=lookback_days).max()
    rlow = low.iloc[:-1, :].rolling(window=lookback_days).min()
    return rhigh, rlow
```
The test fail

**Comment by ayatsuro** [comment]
my bad, just had to shift...

**Comment by sbaner03** [comment]
def getmaxmin(df, lookback_days, flag):
    df = low
    df_T = df.tail(lookback_days+1)[:-1].T
    if flag == 'max':
        df_T['Date'] = df_T.idxmax(axis=1)
        df_T['Price'] = df_T.max(axis=1)
    else: 
        df_T['Date'] = df_T.idxmin(axis=1)
        df_T['Price'] = df_T.min(axis=1)
    return df_T[['Date','Price']]

    lookback_high = getmaxmin(high, 50,'max')
lookback_high.head()

date	Date	Price
ticker		
A	2017-06-02	60.08157294
AAL	2017-06-08	49.97839208
AAP	2017-05-19	147.51033966
AAPL	2017-05-15	152.66046175
ABBV	2017-06-28	70.20045507

I have written a function to generate the lookback_high and lookback_low. but the shape of the data frame that I seem to be getting is incorrect. Could someone please help
