### ISSUE TITLE
Can't import "quiz_tests" package (Lesson 24, PCA Exercise, AI for Trading)

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#52]
Hi! Seems like we have technical issues with Lesson 24, PCA exercise. I can't run the last cell, where worksheet can't import "quiz_tests" package. Thanks!

**Comment by lizotto** [comment]
Ok—thanks for catching this. We'll make the fix ASAP!!

**Comment by lizotto** [comment]
Sorry about that. Hope it works now. Don't forget to "reset data".
