### ISSUE TITLE
Lesson 25 part 19: definition of "forward asset returns"

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#57]
This definition is first mentioned in the quiz. It is not clear, what is meant by "forward asset returns". One can probably guess, but you cannot be sure, if it is not defined explicitly in the lesson.

**Comment by e7dud7e** [comment]
Hi Jevgeni! Thanks for pointing this out.  The lesson doesn't provide this definition until later, so I added a text before the quiz to define it.  Thanks!

###### Forward returns
For this quiz, note that forward return refers to a return that is in the future, or “forward” in time...compared to when the alpha value was calculated.  So, if the alpha values are calculated before time “t”, then the forward asset return is calculated with data that occurs later, from time t to time t plus one.  We'll discuss this in a video in a little bit later in this lesson.

**Comment by jevgenitolstouhhov** [comment]
Thanks Eddy! The mechanics of calculation is clear and  not hard to guess. I was just thinking that maybe we could bring more explanation (semantics) about the essence of "forward returns". Like, are these actually "projected" returns based on our model ? Thanks!
