### ISSUE TITLE
Lesson 25 part 20: the url isn't anchoring to the right location on the page

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#58]
One thing, of course is that we can see underlying HTML text, which needs to be fixed anyway. Then if we click on what is clickable there, we get this in address bar to the browser:
 https://quantopian.github.io/alphalens/alphalens.html?highlight=alphalens%20performance#alphalens.utils.get_clean_factor_and_forward_returns”

Quotation mark in the end is included, yes. Everything works right if you remove quotation mark. Otherwise, the URL is not jumping to the right location on the page.

There were other examples of such kind of  URLs with anchoring issues. Please walk through the earlier pages  within the same lesson and fix those as well (and please also check parts that come after part 20, which we haven't discovered yet). Thanks!

**Comment by jevgenitolstouhhov** [comment]
Same issue for Lesson 25 part 30

**Comment by jevgenitolstouhhov** [comment]
Same issue for Lesson 25 part 41

**Comment by e7dud7e** [comment]
Thanks Jevgeni! I've updated these (there are different quotation marks in the word processor that don't work in the website). Thank you! ^_^
