### ISSUE TITLE
Lesson 25 part 42 answer 3: smoothed factor is not gradually increasing

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#62]
Which (according to lecture materials) should be the first indication that something is wrong with the factor. Why is the correct answer saying that we should prefer the smoothed one?Or is it that one special case, where it is OK to have such non-gradually increasing diagram?

**Comment by e7dud7e** [comment]
Hi Jevgeni, I think your question might be good to share with the rest of the students.  Would you mind re-posting it in the Knowledge forum (the light bulb icon on the left)?  Then I we can follow up.  Thanks!  Here's a link to the Knowledge forum: https://knowledge.udacity.com/?nanodegree=c11b7c24-9f2b-11e8-af93-13785c71f3c2

**Comment by jevgenitolstouhhov** [comment]
Hi Eddy! I have posted this to knowledge base now. I really appreciate your attention and help! :)

**Comment by e7dud7e** [comment]
Answered re-posted question in Knowledge ^_^
