### ISSUE TITLE
Lesson 26 part 6: "Build pipeline engine" can't run

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#63]
ValueError: no data for bundle 'eod-quotemedia' on or before 2018-11-09 13:04:18.163316+00:00
maybe you need to run: $ zipline ingest -b eod-quotemedia

**Comment by jevgenitolstouhhov** [comment]
Same issue for solution notebook too

**Comment by jevgenitolstouhhov** [comment]
Same problem with Lesson 26 part 12

**Comment by e7dud7e** [comment]
Hi Jevgeni, thanks for pointing out this issue!  I've updated the code to find the data correctly.  Could you do Menu -> "reset data" to update those code exercises?

**Comment by jevgenitolstouhhov** [comment]
Works perfectly now for both parts 6 and 12. Thank you!
