### ISSUE TITLE
Lesson 22 part 3: Historical Variance Exercise missing module cvxpy

### ISSUE THREAD

**Issue by maisogjm** [udacity/aitnd-issues#64]
After running the first code cell in the Jupyter notebook, the second code cell bombs out with error "ModuleNotFoundError: No module named 'cvxpy'". Apparently the cvxpy module was not successfully installed by the first code cell, which is supposed to set up the environment.

Running the first code cell seems to complete without errors, although a warning message does appear: "You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

**Comment by e7dud7e** [comment]
Hi Maisogjm! Thanks for telling us about this issue.  I just ran the installation and was not able to get that error message.  If you go to "Menu" and the bottom left of the workspace, and "reset data", can you let us know if you still get that error? thanks!

**Comment by maisogjm** [comment]
Hi, thanks, that worked! Please close out that ticket (or is that something
that needs to be done by me, since I submitted it?)..

Best regards,

joe

**Comment by e7dud7e** [comment]
Thanks! Sure I’ll close the ticket. No need for you to do anything :)
