### ISSUE TITLE
Lesson 26 part 10: Understanding correct quiz answer

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#65]
In the quiz there are 3 correct answers: one of them is obvious answer and another two (regarding shorting growing stocks) is not obvious.

What quiz answer (in my opinion) explain is that there can be the situations, where you might want to short even growing stocks.

I think that there is a little bit not enough context to come up with idea of shorting growing stocks.

Also, if we generalise the explanation of the answer even more, what it actually means is that depending on my risk model or factor model I can go whatever direction with whatever stock, if my factor model or risk model requires doing this.

I would propose that all 4 answers should be correct.. Or the answer should be: "it depends...."

**Comment by e7dud7e** [comment]
Hi Jevgeni, that's a good point; I guess to make it more specific, I could ask students to assume that we aren't yet using a risk model for portfolio optimization.  Risk neutralization and market neutralization is still recommended on alpha factors (before using the risk model).

**Comment by e7dud7e** [comment]
reworded quiz prompt for (alpha factor research case studies) atom 11.
