### ISSUE TITLE
Project 4: Factor Covariance Matrix - expected reset differs from the spec

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#70]
As mentioned in the specification, the result should be DataFrame 
Returns
    -------
    factor_cov_matrix : DataFrame
        Factor covariance matrix

In reality (when you run the code), unit test expects ndarray

**Comment by Brok-Bucholtz** [comment]
Changed the docstring for `factor_cov_matrix` to say "2 dimensional Ndarray" instead of "DataFrame".
