### ISSUE TITLE
Learning Plan emails not sent after first 2 weeks

### ISSUE THREAD

**Issue by e7dud7e** [udacity/aitnd-issues#72]
From Marco C. in study hub: "Hi mates, in the first 2 weeks I have been receiving an email from Udacity with the Learning Plan (and I have found it useful). I am not receiving it anymore, do you have the same issue?"

**Comment by lizotto** [comment]
@e7dud7e How do we find the original question in study hub?

**Comment by lizotto** [comment]
The answer is that we don't have Learning Plans beyond the first two weeks. But we now have Program Home to help people plan their learning.

**Comment by e7dud7e** [comment]
I think I found it in the "my classmates" channel.

**Comment by lizotto** [comment]
Responded in study hub.
