### ISSUE TITLE
Clarify if students can download eod-quotemedia.csv for github

### ISSUE THREAD

**Issue by e7dud7e** [udacity/aitnd-issues#75]
From Florian E:
>Hi @EddyS, I am planning to do my projects locally and later commit it to my github. Same as @VesselinD , I am looking for the eod-quotemedia.csv, in my case and possibly in both cases it is about project1. I know how to download the file from the workspace, but want to make sure that this is ok, especially as I am planning upload it to my github repo.

tasks:
1) can students download the csv file?  Is this a problem for us?
2) can students put the data in their github repo? Is this a problem for us?
3) Can we show students how to use quandl's free data set to work on their projects on local machine?

**Comment by Brok-Bucholtz** [comment]
@e7dud7e 
Is this from the classroom? Can you provide a link to the conversation?

**Comment by e7dud7e** [comment]
yes, in student hub.  I think I tagged you in that conversation, so you may have gotten an email notification.  But I don't know if that would send you directly to the conversation.
