### ISSUE TITLE
Project 1: AttributeError: module 'plotly.graph_objs' has no attribute 'Table'

### ISSUE THREAD

**Issue by maisogjm** [udacity/aitnd-issues#8]
After stepping through the first few cells in the Jupyter notebook for Project 1 in the Artificial Intelligence for Trading Nanodegree Program (including the cell that installs packages), the Code cell in the section entitled "View Data" generates the following error:
AttributeError: module 'plotly.graph_objs' has no attribute 'Table'

**Comment by maisogjm** [comment]
I am no longer able to generate this error! I just re-tried the cell, and it no longer appears. Let's close this issue. If someone has the same problem later, they can re-open it.

**Comment by andersonzhu** [comment]
I got the same error. Please help. @Brok-Bucholtz
