### ISSUE TITLE
regression: exercise error

### ISSUE THREAD

**Issue by e7dud7e** [udacity/aitnd-issues#80]
student feedback: I think overall it is fine to say check the documentation in scikit-learn to figure out how to get the intercept & coefficient but when you provide a suggestion as in "use coef_[0][0]" and "use intercept_[0]" this is a bit misleading. \ \ I am starting to catch fewer and fewer typos in the markdown cells that describe the exercises...

**Comment by lizotto** [comment]
@e7dud7e Who made this exercise?

**Comment by e7dud7e** [comment]
me =P

**Comment by e7dud7e** [comment]
Updated the instructions.
