### ISSUE TITLE
unexpected keyword argument 'freq'

### ISSUE THREAD

**Issue by prabhu15sep** [udacity/aitnd-issues#86]
This error happens only when i execute the code in my local machine. No issues when executed online workspace.

**Comment by prabhu15sep** [comment]
In Lesson 26, concept 15-PCA coding exercise doesnt work well when the notebook is exported to local . It gives me below error:-
##########################################################
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e91f670db46f> in <module>()
      2 
      3 # Get the returns for the fiven start and end date. Both dates must be valid trading dates
----> 4 returns = utils.get_returns(start_date='2011-01-05', end_date='2016-01-05')
      5 
      6 # Display the first rows of the returns

/Volumes/2/Files/OneDrive/Udacity AI trading/Lesson 24/PCA Coding/utils.py in get_returns(start_date, end_date)
     94     # Get the historical data for the given window
     95     historical_data = get_pricing(data_portal, trading_calendar, universe_tickers,
---> 96                                   start_d=start_date, end_d=end_date)
     97 
     98     return historical_data.pct_change()[1:].fillna(0)

/Volumes/2/Files/OneDrive/Udacity AI trading/Lesson 24/PCA Coding/utils.py in get_pricing(data_portal, trading_calendar, assets, start_d, end_d, field)
     75     # Set the given start and end dates to Timestamps. The frequency string C is used to
     76     # indicate that a CustomBusinessDay DateOffset is used
---> 77     end_dt = pd.Timestamp(end_d, tz='UTC', freq='C')
     78     start_dt = pd.Timestamp(start_d, tz='UTC', freq='C')
     79 

pandas/tslib.pyx in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:9139)()

TypeError: __new__() got an unexpected keyword argument 'freq'
##############################################################
The error subsides only when ", freq='C'" arguement is not provided i the utlis.py file. See Line 77 above for the arguement

**Comment by juanudacity** [comment]
What version of Pandas are you running locally?
