### ISSUE TITLE
Term 2: Lesson 8, part 16

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [udacity/aitnd-issues#94]
From the exercise below, if we just return empty list, the unit test says that the answer is correct.

Trying for L=[5,6,7].
The correct answer is
[0.09003057317038046, 0.24472847105479764, 0.6652409557748219]
And your code returned
[]

Correct!

**Comment by Brok-Bucholtz** [comment]
Thanks for the feedback. We have fixed the quiz to correctly check the solution.
