### ISSUE TITLE
Historical Variance

### ISSUE THREAD

**Issue by cmkwong** [udacity/aitnd-issues#96]
After install the library, it has error still:
ImportError: cannot import name 'ABCIndexClass'

**Comment by lizotto** [comment]
Hi @cmkwong, in what part of the course does this error occur? Can you give the lesson #?

**Comment by e7dud7e** [comment]
Hi! Thanks for notifying us.  I wasn't able to re-produce this error.  Could you try to refresh your workspace using "reset data"?  If you still get this error, please let us know, thank you!

**Comment by cmkwong** [comment]
The issue occurs in Term 1 Lesson 24-4. It seems no problem now when Kernel > Restart and Run All. But I need to install every time when I restart the jupyter notebook?

**Comment by Brok-Bucholtz** [comment]
This is a duplicate of Issue #85.
